# Generated by Django 3.0.2 on 2020-01-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0002_auto_20200108_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='q01',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q02',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q03',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q04',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q05',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q06',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q07',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q08',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q09',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q10',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q11',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q12',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q13',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q14',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q15',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q16',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q17',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q18',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q19',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='q20',
            field=models.IntegerField(choices=[(0, '극히 드물다'), (1, '가끔 있었다'), (2, '종종 있었다'), (3, '대부분 그랬다')], default=0),
        ),
    ]
